### PR TITLE
fixes #24 removed rewrite for Mage_Adminhtml_Block_Sales_Order_Grid

### PR DESCRIPTION
**Pull request by sreichel**

### CODE REVIEW

**Comment by sreichel** [comment]
Sorry for late response ... it seems i have not commited all files. I can reproduce it and will tale a look at it during next days.

**Comment by sreichel** [comment]
Tested with 1.5.0.1 and 1.9.x without any problems.

**Comment by sasoriza** [comment]
The version available at Magento Connect differs from the version available on github. I tried this again using the github files and it seems to be working.

I am however seeing these two rewrites:

sales_resource/order_grid_collection 	Magemaven_OrderComment_Model_Resource_Order_Grid_Collection 	Magemaven_OrderComment_Model_Mysql4_Order_Grid_Collection

sales_mysql4/order_grid_collection 	Magemaven_OrderComment_Model_Mysql4_Order_Grid_Collection 	Mage_Sales_Mysql4_Model_Order_Grid_Collection

Is this intended to be like that?

**Comment by sasoriza** [comment]
Downloading the full package from https://github.com/sreichel/magento-order-comment seemed to do the trick. I must have done something wrong when manually replacing the files.

**Pull request closed without merging**
